sudo: required

language: python

services:
    - docker

cache:
    directories:
        - $HOME/.cache/pip

matrix:
    include:
        - env:TOX_ENV=py35
          python: 3.5

        - env: TOX_ENV=py36
          python: 3.6

        - env: TOX_ENC=py37
          python: 3.7

install:
    - pip install -U tox

script: travis_retry tox -e $TOX_ENV

after_success:
    - python test.py
    - docker-compose --file ../output/sanic-test/docker-compose.yaml

