version: '3'
services:
    postgres:
        restart: always
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: password
        env_file: .env
        ports:
            - "5432:5432"
        volumes:
            - {{cookiecutter.postgres_volume_location}}:/var/lib/postgresql/data
        networks:
          - sanic

    {{cookiecutter.app_name}}:
        restart: always
        build:
            context: .
        ports:
            - "{{cookiecutter.sanic_port}}:{{cookiecutter.sanic_port}}"
        env_file: .env
        environment:
            SANIC_DB_HOST: postgres
            SANIC_DB_PASSWORD: password
            SANIC_DB_DATABASE: postgres
        depends_on:
            - postgres
        links:
            - postgres
        networks:
            - sanic

volumes:
    {{cookiecutter.postgres_volume_location}}:
        driver: local

networks:
    sanic
